import { LogEntry } from "./types";

export const severityColors: Record<LogEntry["severity"], string> = {
  error: "bg-red-500/20 text-red-600",
  warning: "bg-yellow-500/20 text-yellow-600",
  info: "bg-blue-500/20 text-blue-600",
  normal: "bg-green-500/20 text-green-600",
  critical: "bg-purple-500/20 text-purple-600",
};

export const MOCK_LOGS: LogEntry[] = [
    {
      id: "1",
      timestamp: "2024-01-23 10:15:30",
      severity: "error",
      service: "authentication",
      message: "Multiple failed login attempts detected",
      details: {
        ipAddress: "192.168.1.100",
        userAgent: "Mozilla/5.0",
        additionalInfo: "Potential brute force attack",
      },
    },
    {
      id: "2",
      timestamp: "2024-01-23 11:20:45",
      severity: "warning",
      service: "database",
      message: "High memory usage detected",
      details: {
        memoryUsage: "85%",
        process: "mysql",
        recommendedAction: "Optimize queries or scale resources",
      },
    },
    {
      id: "3",
      timestamp: "2024-01-23 11:21:00",
      severity: "error",
      service: "authentication",
      message: "Failed login attempt",
      details: {
        username: "johndoe",
        ip_address: "192.168.1.101",
        reason: "Invalid credentials",
      },
    },
    {
      id: "4",
      timestamp: "2024-01-23 11:21:15",
      severity: "warning",
      service: "database",
      message: "High disk usage detected",
      details: {
        current_usage: "90%",
        threshold: "85%",
        affected_table: "users",
      },
    },
    {
      id: "5",
      timestamp: "2024-01-23 11:21:30",
      severity: "info",
      service: "network",
      message: "Network interface up",
      details: {
        interface_name: "eth1",
        ip_address: "192.168.2.100",
        subnet_mask: "255.255.255.0",
      },
    },
    {
      id: "6",
      timestamp: "2024-01-23 11:21:45",
      severity: "critical",
      service: "security",
      message: "Unauthorized access attempt",
      details: {
        source_ip: "192.168.1.200",
        target_port: "22",
        protocol: "SSH",
      },
    },
    {
      id: "7",
      timestamp: "2024-01-23 11:22:00",
      severity: "error",
      service: "application",
      message: "Exception thrown",
      details: {
        exception_type: "NullPointerException",
        stack_trace: "com.example.MyClass.myMethod(MyClass.java:42)",
        affected_user: "jane_smith",
      },
    },
    {
      id: "8",
      timestamp: "2024-01-23 11:22:15",
      severity: "warning",
      service: "filesystem",
      message: "Low free space warning",
      details: {
        drive_letter: "C:",
        free_space: "5GB",
        total_capacity: "500GB",
        threshold: "5%",
      },
    },
    {
      id: "9",
      timestamp: "2024-01-23 11:22:30",
      severity: "info",
      service: "backup",
      message: "Backup completed successfully",
      details: {
        backup_type: "full",
        size: "100GB",
        duration: "120 minutes",
        destination: "/mnt/backup",
      },
    },
    {
      id: "10",
      timestamp: "2024-01-23 11:22:45",
      severity: "critical",
      service: "database_replication",
      message: "Replication lag exceeded threshold",
      details: {
        replication_lag: "300 seconds",
        acceptable_lag: "180 seconds",
        primary_server: "db-master",
        replica_server: "db-replica-1",
      },
    },
    {
      id: "11",
      timestamp: "2024-01-23 11:23:00",
      severity: "warning",
      service: "cpu_monitoring",
      message: "High CPU usage detected",
      details: {
        current_usage: "95%",
        threshold: "90%",
        affected_process: "java.exe",
        pid: "1234",
      },
    },
    {
      id: "12",
      timestamp: "2024-01-23 11:23:15",
      severity: "error",
      service: "network_security",
      message: "Suspicious traffic pattern detected",
      details: {
        source_ip: "192.168.1.150",
        destination_port: "443",
        packet_count: "500",
        time_window: "5 minutes",
      },
    },
    {
      id: "13",
      timestamp: "2024-01-23 11:23:30",
      severity: "info",
      service: "user_management",
      message: "User account locked",
      details: {
        user_id: "user456",
        lock_reason: "Excessive failed login attempts",
        unlock_time: "2024-01-23 12:23:30",
        attempt_count: "5",
      },
    },
    {
      id: "14",
      timestamp: "2024-01-23 11:23:45",
      severity: "critical",
      service: "high_availability",
      message: "Cluster node failure",
      details: {
        failed_node: "node-2",
        cluster_name: "prod-cluster",
        failure_reason: "Hardware failure",
        remaining_nodes: "3",
      },
    },
    {
      id: "15",
      timestamp: "2024-01-23 11:24:00",
      severity: "warning",
      service: "memory_monitoring",
      message: "Low available memory warning",
      details: {
        current_available: "2GB",
        threshold: "1GB",
        affected_process: "chrome.exe",
        pid: "5678",
      },
    },
    {
      id: "16",
      timestamp: "2024-01-23 11:24:15",
      severity: "error",
      service: "email_service",
      message: "Email delivery failure",
      details: {
        recipient: "john@example.com",
        subject: "Order Confirmation",
        error_reason: "SMTP connection timed out",
        retry_count: "2",
      },
    },
    {
      id: "17",
      timestamp: "2024-01-23 11:24:30",
      severity: "info",
      service: "deployment",
      message: "New application version deployed",
      details: {
        application_name: "myapp",
        version: "v2.1.0",
        environment: "production",
        deployment_time: "2024-01-23 11:24:30",
      },
    },
  ];